### ISSUE TITLE
Support for osx-arm64

### ISSUE THREAD

**Issue by joshualeond** [conda-forge/r-cmdstanr-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi there, I recently posted a question around platform support for `cmdstanr` on the Stan forums: [cmdstanr on Apple M1 from conda-forge](https://discourse.mc-stan.org/t/cmdstanr-on-apple-m1-from-conda-forge/34760) and was pointed here.

It looks like `cmdstanr` limits the supported platforms compared to `cmdstanpy` and `cmdstan` itself. 

Can `cmdstanr` on conda-forge be updated to include `osx-arm64` like the others? Thank you!

## cmdstanr

<img width="143" alt="image" src="https://github.com/conda-forge/r-cmdstanr-feedstock/assets/3802502/36011541-45e2-4b01-a2f9-dacce4e9b01e">

## cmdstanpy

This one looks to support any platform:
<img width="149" alt="image" src="https://github.com/conda-forge/r-cmdstanr-feedstock/assets/3802502/a99e066f-7a3a-4b5a-8f9f-3850cba861c4">

## cmdstan
This one shows `osx-arm64` support explicitly:
<img width="295" alt="image" src="https://github.com/conda-forge/r-cmdstanr-feedstock/assets/3802502/23d1268a-3f4e-405c-9f6e-6aaa0ed88524">

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mfansler** [comment]
Thanks for expressing your desire for having the **osx-arm64** platform supported by this feedstock. Directions for requesting such builds can be found in the Knowledge Base: https://conda-forge.org/docs/maintainer/knowledge_base/#apple-silicon-builds. Let me know if you need any help initiating this! I'll try to keep an eye out for the corresponding migration PR.

**Comment by joshualeond** [comment]
Thank you @mfansler! 

I submitted the PR here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5760

Please let me know if I need to do anything else.

**Comment by mfansler** [comment]
@joshualeond after looking at the package more closely turns out it should have been `noarch` all along. Apologies for having you unnecessarily go through the migration process. I've converted it and the new builds will be compatible with all platforms. Should be available in 1-2 hours.

Feel free to follow up with any issues, and thanks again!

**Comment by joshualeond** [comment]
Thank you @mfansler! I tested this last night and everything worked perfectly. I appreciate you helping me out with this.
